<?php
/**
 * ProfileAssignmentsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  EC\EUAccess\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EU Access Users API
 *
 * EU Access Users API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: DIGIT-EU-ACCESS@ec.europa.eu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EC\EUAccess\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use EC\EUAccess\Client\ApiException;
use EC\EUAccess\Client\Configuration;
use EC\EUAccess\Client\HeaderSelector;
use EC\EUAccess\Client\ObjectSerializer;

/**
 * ProfileAssignmentsApi Class Doc Comment
 *
 * @category Class
 * @package  EC\EUAccess\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProfileAssignmentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createProfileAssignment' => [
            'application/json',
        ],
        'deleteProfileAssignment' => [
            'application/json',
        ],
        'getProfileAssignment' => [
            'application/json',
        ],
        'getProfileAssignments' => [
            'application/json',
        ],
        'updateProfileAssignment' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createProfileAssignment
     *
     * Create a profile assignment for an identity
     *
     * @param  \EC\EUAccess\Client\Model\ProfileAssignmentCreateRequest $request ProfileAssignment object (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProfileAssignment'] to see the possible values for this operation
     *
     * @throws \EC\EUAccess\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EC\EUAccess\Client\Model\ProfileAssignmentId|\EC\EUAccess\Client\Model\ErrorMessage|\EC\EUAccess\Client\Model\ErrorMessage|\EC\EUAccess\Client\Model\ErrorMessage
     */
    public function createProfileAssignment($request, string $contentType = self::contentTypes['createProfileAssignment'][0])
    {
        list($response) = $this->createProfileAssignmentWithHttpInfo($request, $contentType);
        return $response;
    }

    /**
     * Operation createProfileAssignmentWithHttpInfo
     *
     * Create a profile assignment for an identity
     *
     * @param  \EC\EUAccess\Client\Model\ProfileAssignmentCreateRequest $request ProfileAssignment object (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProfileAssignment'] to see the possible values for this operation
     *
     * @throws \EC\EUAccess\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \EC\EUAccess\Client\Model\ProfileAssignmentId|\EC\EUAccess\Client\Model\ErrorMessage|\EC\EUAccess\Client\Model\ErrorMessage|\EC\EUAccess\Client\Model\ErrorMessage, HTTP status code, HTTP response headers (array of strings)
     */
    public function createProfileAssignmentWithHttpInfo($request, string $contentType = self::contentTypes['createProfileAssignment'][0])
    {
        $request = $this->createProfileAssignmentRequest($request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\EC\EUAccess\Client\Model\ProfileAssignmentId' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\EUAccess\Client\Model\ProfileAssignmentId' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\EUAccess\Client\Model\ProfileAssignmentId', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\EC\EUAccess\Client\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\EUAccess\Client\Model\ErrorMessage' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\EUAccess\Client\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\EC\EUAccess\Client\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\EUAccess\Client\Model\ErrorMessage' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\EUAccess\Client\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\EC\EUAccess\Client\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\EUAccess\Client\Model\ErrorMessage' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\EUAccess\Client\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EC\EUAccess\Client\Model\ProfileAssignmentId';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ProfileAssignmentId',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createProfileAssignmentAsync
     *
     * Create a profile assignment for an identity
     *
     * @param  \EC\EUAccess\Client\Model\ProfileAssignmentCreateRequest $request ProfileAssignment object (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProfileAssignment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createProfileAssignmentAsync($request, string $contentType = self::contentTypes['createProfileAssignment'][0])
    {
        return $this->createProfileAssignmentAsyncWithHttpInfo($request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createProfileAssignmentAsyncWithHttpInfo
     *
     * Create a profile assignment for an identity
     *
     * @param  \EC\EUAccess\Client\Model\ProfileAssignmentCreateRequest $request ProfileAssignment object (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProfileAssignment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createProfileAssignmentAsyncWithHttpInfo($request, string $contentType = self::contentTypes['createProfileAssignment'][0])
    {
        $returnType = '\EC\EUAccess\Client\Model\ProfileAssignmentId';
        $request = $this->createProfileAssignmentRequest($request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createProfileAssignment'
     *
     * @param  \EC\EUAccess\Client\Model\ProfileAssignmentCreateRequest $request ProfileAssignment object (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProfileAssignment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createProfileAssignmentRequest($request, string $contentType = self::contentTypes['createProfileAssignment'][0])
    {

        // verify the required parameter 'request' is set
        if ($request === null || (is_array($request) && count($request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request when calling createProfileAssignment'
            );
        }


        $resourcePath = '/v1.0/profileAssignments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($request));
            } else {
                $httpBody = $request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteProfileAssignment
     *
     * Deletes a profile assignment
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteProfileAssignment'] to see the possible values for this operation
     *
     * @throws \EC\EUAccess\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteProfileAssignment($profile_assignment_id, string $contentType = self::contentTypes['deleteProfileAssignment'][0])
    {
        $this->deleteProfileAssignmentWithHttpInfo($profile_assignment_id, $contentType);
    }

    /**
     * Operation deleteProfileAssignmentWithHttpInfo
     *
     * Deletes a profile assignment
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteProfileAssignment'] to see the possible values for this operation
     *
     * @throws \EC\EUAccess\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteProfileAssignmentWithHttpInfo($profile_assignment_id, string $contentType = self::contentTypes['deleteProfileAssignment'][0])
    {
        $request = $this->deleteProfileAssignmentRequest($profile_assignment_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteProfileAssignmentAsync
     *
     * Deletes a profile assignment
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteProfileAssignment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteProfileAssignmentAsync($profile_assignment_id, string $contentType = self::contentTypes['deleteProfileAssignment'][0])
    {
        return $this->deleteProfileAssignmentAsyncWithHttpInfo($profile_assignment_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteProfileAssignmentAsyncWithHttpInfo
     *
     * Deletes a profile assignment
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteProfileAssignment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteProfileAssignmentAsyncWithHttpInfo($profile_assignment_id, string $contentType = self::contentTypes['deleteProfileAssignment'][0])
    {
        $returnType = '';
        $request = $this->deleteProfileAssignmentRequest($profile_assignment_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteProfileAssignment'
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteProfileAssignment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteProfileAssignmentRequest($profile_assignment_id, string $contentType = self::contentTypes['deleteProfileAssignment'][0])
    {

        // verify the required parameter 'profile_assignment_id' is set
        if ($profile_assignment_id === null || (is_array($profile_assignment_id) && count($profile_assignment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $profile_assignment_id when calling deleteProfileAssignment'
            );
        }


        $resourcePath = '/v1.0/profileAssignments/{profileAssignmentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($profile_assignment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'profileAssignmentId' . '}',
                ObjectSerializer::toPathValue($profile_assignment_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getProfileAssignment
     *
     * Get the profile assignment with the given id
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfileAssignment'] to see the possible values for this operation
     *
     * @throws \EC\EUAccess\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EC\EUAccess\Client\Model\ProfileAssignment|\EC\EUAccess\Client\Model\ErrorMessage|\EC\EUAccess\Client\Model\ErrorMessage|\EC\EUAccess\Client\Model\ErrorMessage
     */
    public function getProfileAssignment($profile_assignment_id, string $contentType = self::contentTypes['getProfileAssignment'][0])
    {
        list($response) = $this->getProfileAssignmentWithHttpInfo($profile_assignment_id, $contentType);
        return $response;
    }

    /**
     * Operation getProfileAssignmentWithHttpInfo
     *
     * Get the profile assignment with the given id
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfileAssignment'] to see the possible values for this operation
     *
     * @throws \EC\EUAccess\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \EC\EUAccess\Client\Model\ProfileAssignment|\EC\EUAccess\Client\Model\ErrorMessage|\EC\EUAccess\Client\Model\ErrorMessage|\EC\EUAccess\Client\Model\ErrorMessage, HTTP status code, HTTP response headers (array of strings)
     */
    public function getProfileAssignmentWithHttpInfo($profile_assignment_id, string $contentType = self::contentTypes['getProfileAssignment'][0])
    {
        $request = $this->getProfileAssignmentRequest($profile_assignment_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\EC\EUAccess\Client\Model\ProfileAssignment' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\EUAccess\Client\Model\ProfileAssignment' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\EUAccess\Client\Model\ProfileAssignment', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\EC\EUAccess\Client\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\EUAccess\Client\Model\ErrorMessage' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\EUAccess\Client\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\EC\EUAccess\Client\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\EUAccess\Client\Model\ErrorMessage' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\EUAccess\Client\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\EC\EUAccess\Client\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\EUAccess\Client\Model\ErrorMessage' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\EUAccess\Client\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EC\EUAccess\Client\Model\ProfileAssignment';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ProfileAssignment',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getProfileAssignmentAsync
     *
     * Get the profile assignment with the given id
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfileAssignment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProfileAssignmentAsync($profile_assignment_id, string $contentType = self::contentTypes['getProfileAssignment'][0])
    {
        return $this->getProfileAssignmentAsyncWithHttpInfo($profile_assignment_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProfileAssignmentAsyncWithHttpInfo
     *
     * Get the profile assignment with the given id
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfileAssignment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProfileAssignmentAsyncWithHttpInfo($profile_assignment_id, string $contentType = self::contentTypes['getProfileAssignment'][0])
    {
        $returnType = '\EC\EUAccess\Client\Model\ProfileAssignment';
        $request = $this->getProfileAssignmentRequest($profile_assignment_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProfileAssignment'
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfileAssignment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getProfileAssignmentRequest($profile_assignment_id, string $contentType = self::contentTypes['getProfileAssignment'][0])
    {

        // verify the required parameter 'profile_assignment_id' is set
        if ($profile_assignment_id === null || (is_array($profile_assignment_id) && count($profile_assignment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $profile_assignment_id when calling getProfileAssignment'
            );
        }


        $resourcePath = '/v1.0/profileAssignments/{profileAssignmentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($profile_assignment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'profileAssignmentId' . '}',
                ObjectSerializer::toPathValue($profile_assignment_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getProfileAssignments
     *
     * Get profile assignments for the given identity id
     *
     * @param  int $identity_id The user&#39;s identity id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfileAssignments'] to see the possible values for this operation
     *
     * @throws \EC\EUAccess\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EC\EUAccess\Client\Model\ProfileAssignment[]|\EC\EUAccess\Client\Model\ErrorMessage|\EC\EUAccess\Client\Model\ErrorMessage|\EC\EUAccess\Client\Model\ErrorMessage
     */
    public function getProfileAssignments($identity_id, string $contentType = self::contentTypes['getProfileAssignments'][0])
    {
        list($response) = $this->getProfileAssignmentsWithHttpInfo($identity_id, $contentType);
        return $response;
    }

    /**
     * Operation getProfileAssignmentsWithHttpInfo
     *
     * Get profile assignments for the given identity id
     *
     * @param  int $identity_id The user&#39;s identity id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfileAssignments'] to see the possible values for this operation
     *
     * @throws \EC\EUAccess\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \EC\EUAccess\Client\Model\ProfileAssignment[]|\EC\EUAccess\Client\Model\ErrorMessage|\EC\EUAccess\Client\Model\ErrorMessage|\EC\EUAccess\Client\Model\ErrorMessage, HTTP status code, HTTP response headers (array of strings)
     */
    public function getProfileAssignmentsWithHttpInfo($identity_id, string $contentType = self::contentTypes['getProfileAssignments'][0])
    {
        $request = $this->getProfileAssignmentsRequest($identity_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\EC\EUAccess\Client\Model\ProfileAssignment[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\EUAccess\Client\Model\ProfileAssignment[]' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\EUAccess\Client\Model\ProfileAssignment[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\EC\EUAccess\Client\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\EUAccess\Client\Model\ErrorMessage' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\EUAccess\Client\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\EC\EUAccess\Client\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\EUAccess\Client\Model\ErrorMessage' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\EUAccess\Client\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\EC\EUAccess\Client\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\EUAccess\Client\Model\ErrorMessage' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\EUAccess\Client\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EC\EUAccess\Client\Model\ProfileAssignment[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ProfileAssignment[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getProfileAssignmentsAsync
     *
     * Get profile assignments for the given identity id
     *
     * @param  int $identity_id The user&#39;s identity id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfileAssignments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProfileAssignmentsAsync($identity_id, string $contentType = self::contentTypes['getProfileAssignments'][0])
    {
        return $this->getProfileAssignmentsAsyncWithHttpInfo($identity_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProfileAssignmentsAsyncWithHttpInfo
     *
     * Get profile assignments for the given identity id
     *
     * @param  int $identity_id The user&#39;s identity id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfileAssignments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProfileAssignmentsAsyncWithHttpInfo($identity_id, string $contentType = self::contentTypes['getProfileAssignments'][0])
    {
        $returnType = '\EC\EUAccess\Client\Model\ProfileAssignment[]';
        $request = $this->getProfileAssignmentsRequest($identity_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProfileAssignments'
     *
     * @param  int $identity_id The user&#39;s identity id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfileAssignments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getProfileAssignmentsRequest($identity_id, string $contentType = self::contentTypes['getProfileAssignments'][0])
    {

        // verify the required parameter 'identity_id' is set
        if ($identity_id === null || (is_array($identity_id) && count($identity_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $identity_id when calling getProfileAssignments'
            );
        }


        $resourcePath = '/v1.0/profileAssignments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $identity_id,
            'identityId', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateProfileAssignment
     *
     * Update a profile assignment with the given id
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  \EC\EUAccess\Client\Model\ProfileAssignmentUpdateRequest $request The profile assignment object to update (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateProfileAssignment'] to see the possible values for this operation
     *
     * @throws \EC\EUAccess\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function updateProfileAssignment($profile_assignment_id, $request, string $contentType = self::contentTypes['updateProfileAssignment'][0])
    {
        $this->updateProfileAssignmentWithHttpInfo($profile_assignment_id, $request, $contentType);
    }

    /**
     * Operation updateProfileAssignmentWithHttpInfo
     *
     * Update a profile assignment with the given id
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  \EC\EUAccess\Client\Model\ProfileAssignmentUpdateRequest $request The profile assignment object to update (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateProfileAssignment'] to see the possible values for this operation
     *
     * @throws \EC\EUAccess\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateProfileAssignmentWithHttpInfo($profile_assignment_id, $request, string $contentType = self::contentTypes['updateProfileAssignment'][0])
    {
        $request = $this->updateProfileAssignmentRequest($profile_assignment_id, $request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\EUAccess\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateProfileAssignmentAsync
     *
     * Update a profile assignment with the given id
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  \EC\EUAccess\Client\Model\ProfileAssignmentUpdateRequest $request The profile assignment object to update (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateProfileAssignment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateProfileAssignmentAsync($profile_assignment_id, $request, string $contentType = self::contentTypes['updateProfileAssignment'][0])
    {
        return $this->updateProfileAssignmentAsyncWithHttpInfo($profile_assignment_id, $request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateProfileAssignmentAsyncWithHttpInfo
     *
     * Update a profile assignment with the given id
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  \EC\EUAccess\Client\Model\ProfileAssignmentUpdateRequest $request The profile assignment object to update (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateProfileAssignment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateProfileAssignmentAsyncWithHttpInfo($profile_assignment_id, $request, string $contentType = self::contentTypes['updateProfileAssignment'][0])
    {
        $returnType = '';
        $request = $this->updateProfileAssignmentRequest($profile_assignment_id, $request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateProfileAssignment'
     *
     * @param  int $profile_assignment_id The profile assignment id (required)
     * @param  \EC\EUAccess\Client\Model\ProfileAssignmentUpdateRequest $request The profile assignment object to update (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateProfileAssignment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateProfileAssignmentRequest($profile_assignment_id, $request, string $contentType = self::contentTypes['updateProfileAssignment'][0])
    {

        // verify the required parameter 'profile_assignment_id' is set
        if ($profile_assignment_id === null || (is_array($profile_assignment_id) && count($profile_assignment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $profile_assignment_id when calling updateProfileAssignment'
            );
        }

        // verify the required parameter 'request' is set
        if ($request === null || (is_array($request) && count($request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request when calling updateProfileAssignment'
            );
        }


        $resourcePath = '/v1.0/profileAssignments/{profileAssignmentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($profile_assignment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'profileAssignmentId' . '}',
                ObjectSerializer::toPathValue($profile_assignment_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($request));
            } else {
                $httpBody = $request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
