<?php
/**
 * ErrorType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  EC\EUAccess\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EU Access Users API
 *
 * EU Access Users API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: DIGIT-EU-ACCESS@ec.europa.eu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EC\EUAccess\Client\Model;
use \EC\EUAccess\Client\ObjectSerializer;

/**
 * ErrorType Class Doc Comment
 *
 * @category Class
 * @description The type of error that occurred:   * &#x60;SECURITY_ERROR&#x60; - The error is related to a security issue   * &#x60;USER_ERROR&#x60; - The error is related to an inappropriate use of the API   * &#x60;RUNTIME_ERROR&#x60; - The error is related to a dysfunction at runtime   * &#x60;INTERNAL_ERROR&#x60; - The error is an unexpected software failure
 * @package  EC\EUAccess\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ErrorType
{
    /**
     * Possible values of this enum
     */
    public const SECURITY_ERROR = 'SECURITY_ERROR';

    public const USER_ERROR = 'USER_ERROR';

    public const RUNTIME_ERROR = 'RUNTIME_ERROR';

    public const INTERNAL_ERROR = 'INTERNAL_ERROR';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SECURITY_ERROR,
            self::USER_ERROR,
            self::RUNTIME_ERROR,
            self::INTERNAL_ERROR
        ];
    }
}


