<?php
/**
 * ErrorTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EU Access Users API
 *
 * EU Access Users API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: DIGIT-EU-ACCESS@ec.europa.eu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ErrorTypeTest Class Doc Comment
 *
 * @category    Class
 * @description The type of error that occurred:   * &#x60;SECURITY_ERROR&#x60; - The error is related to a security issue   * &#x60;USER_ERROR&#x60; - The error is related to an inappropriate use of the API   * &#x60;RUNTIME_ERROR&#x60; - The error is related to a dysfunction at runtime   * &#x60;INTERNAL_ERROR&#x60; - The error is an unexpected software failure
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ErrorTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ErrorType"
     */
    public function testErrorType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
